export default {
  nav: { home: 'Главная', rules: 'Правила WAF', analyzer: 'Анализатор', behavioral: 'Поведенческий', logs: 'Журналы', statistics: 'Статистика', blockedIPs: 'Заблокированные IP', proxy: 'Прокси', settings: 'Настройки', howItWorks: 'Как работает', about: 'О программе' },
  home: {
    title: 'Поведенческий анализ WAF', subtitle: 'Файрвол веб-приложений с интеллектуальным анализом поведения', description: 'Продвинутый файрвол, сочетающий сигнатурное обнаружение с анализом поведения на базе ИИ для выявления и блокировки сложных атак.',
    features: { waf: { title: 'Защита WAF', desc: 'Блокировка SQL-инъекций, XSS и других веб-атак' }, behavioral: { title: 'Поведенческий анализ', desc: 'Обнаружение аномалий на основе паттернов поведения' }, realtime: { title: 'Обнаружение в реальном времени', desc: 'Мгновенное обнаружение и реагирование на угрозы' }, learning: { title: 'Адаптивное обучение', desc: 'Непрерывное изучение нормальных паттернов' } },
    startAnalysis: 'Начать анализ', viewLogs: 'Просмотр журналов'
  },
  rules: { title: 'Правила WAF', subtitle: 'Управление правилами файрвола', addRule: 'Добавить правило', columns: { name: 'Название', pattern: 'Шаблон', action: 'Действие', severity: 'Серьёзность', hits: 'Срабатывания', status: 'Статус' }, actions: { block: 'Блокировать', allow: 'Разрешить', challenge: 'Проверка', limit: 'Ограничить', alert: 'Только оповещение' } },
  analyzer: { title: 'Анализатор запросов', subtitle: 'Тестирование и анализ запросов на угрозы', testAttack: 'Тестовая атака', attackTypes: { sql: 'SQL-инъекция', xss: 'XSS-атака', path: 'Обход пути', cmd: 'Инъекция команд', normal: 'Обычный запрос' }, results: { title: 'Результаты', riskScore: 'Оценка риска', action: 'Рекомендуемое действие', threats: 'Обнаруженные угрозы', behavior: 'Поведенческая оценка' } },
  behavioral: { title: 'Поведенческий анализ', subtitle: 'Мониторинг поведения сессий и обнаружение аномалий', sessions: 'Активные сессии', anomalies: 'Обнаруженные аномалии', bots: 'Обнаружение ботов', columns: { session: 'ID сессии', requests: 'Запросы', riskScore: 'Оценка риска', isBot: 'Бот', lastSeen: 'Последняя активность' }, metrics: { typingSpeed: 'Скорость набора', mouseMovement: 'Движение мыши', scrollPattern: 'Паттерн прокрутки', pageViews: 'Просмотры страниц' } },
  logs: { title: 'Журнал атак', subtitle: 'Обнаружение и блокировка атак в реальном времени', columns: { time: 'Время', type: 'Тип атаки', source: 'IP-источник', target: 'Цель', action: 'Действие', riskScore: 'Оценка риска' }, filters: { all: 'Все', blocked: 'Заблокированные', allowed: 'Разрешённые', challenged: 'Проверенные' } },
  statistics: { title: 'Статистика безопасности', subtitle: 'Обзор производительности WAF', overview: { totalRequests: 'Всего запросов', blockedRequests: 'Заблокировано', challengedRequests: 'Проверено', blockRate: 'Процент блокировки' }, charts: { attackTypes: 'Атаки по типам', timeline: 'Временная шкала (24ч)', behavioral: 'Поведенческие метрики' } },
  howItWorks: { title: 'Как работает поведенческий анализ WAF', subtitle: 'Интеллектуальная защита веб-приложений', steps: { step1: { title: 'Перехват запросов', desc: 'Все HTTP-запросы перехватываются и анализируются' }, step2: { title: 'Сигнатурный анализ', desc: 'Проверка по известным шаблонам атак (SQL, XSS и др.)' }, step3: { title: 'Поведенческий анализ', desc: 'Анализ поведения пользователя на аномалии' }, step4: { title: 'Механизм принятия решений', desc: 'Объединение сигналов для решения о блокировке' }, step5: { title: 'Адаптивное обучение', desc: 'Непрерывное обновление поведенческих профилей' } } },
  about: { title: 'О поведенческом анализе WAF', subtitle: 'Интеллектуальная защита веб-приложений', description: 'Дипломный проект демонстрирует файрвол веб-приложений, сочетающий сигнатурное обнаружение с поведенческим анализом для комплексной защиты от известных и неизвестных атак.', author: { title: 'Автор', name: 'Батыр Акыев', project: 'Дипломный проект', topic: 'Файрвол веб-приложений с поведенческим анализом', topicTk: 'Ulanyjynyň hereketine görä işleýän web gorag ulgamy' } },
  common: { loading: 'Загрузка...', error: 'Ошибка', success: 'Успешно', warning: 'Предупреждение' },
  footer: { diploma: 'Дипломный проект', author: 'Автор' },
  settings: { title: 'Настройки', subtitle: 'Настройки системы WAF', emailAlerts: 'Email-оповещения', exportReports: 'Экспорт отчётов', systemInfo: 'Системная информация', dangerZone: 'Опасная зона' },
  blockedIPs: { title: 'Заблокированные IP', subtitle: 'Управление заблокированными адресами', addIP: 'Заблокировать IP', totalBlocked: 'Всего заблокировано', totalBlocks: 'Всего блокировок', countries: 'Страны', ipAddress: 'IP-адрес', reason: 'Причина', blockCount: 'Блокировок', blockedAt: 'Заблокирован', geolocation: 'Геолокация', actions: 'Действия', noBlocked: 'Нет заблокированных адресов', addNewIP: 'Заблокировать новый IP', blockIP: 'Заблокировать' },
  proxy: { title: 'Режим обратного прокси', subtitle: 'Защита внешних сайтов через WAF', howItWorks: 'Как работает прокси', howItWorksDesc: 'WAF выступает защитным слоем между клиентами и целевым сервером. Все запросы анализируются на угрозы перед пересылкой.', configuration: 'Настройка прокси', targetUrl: 'URL целевого сервера', targetName: 'Название цели', proxyPort: 'Порт прокси', logRequests: 'Логировать подозрительные запросы', blockThreats: 'Блокировать угрозы', saveConfig: 'Сохранить', control: 'Управление прокси', running: 'Прокси запущен', stopped: 'Прокси остановлен', stoppedDesc: 'Запустите прокси для защиты сервера', start: 'Запустить', stop: 'Остановить', accessVia: 'Доступ через', accessHint: 'Все запросы будут анализироваться WAF перед пересылкой.', integrationCode: 'Варианты интеграции' },
  login: { subtitle: 'Войдите для доступа к панели WAF', registerSubtitle: 'Создайте новый аккаунт', username: 'Имя пользователя', usernamePlaceholder: 'Введите имя', email: 'Электронная почта', emailPlaceholder: 'Введите email', password: 'Пароль', passwordPlaceholder: 'Введите пароль', confirmPassword: 'Подтвердите пароль', confirmPasswordPlaceholder: 'Повторите пароль', loginButton: 'Войти', registerButton: 'Создать аккаунт', haveAccount: 'Уже есть аккаунт?', noAccount: 'Нет аккаунта?', loginLink: 'Войти', registerLink: 'Регистрация', demoCredentials: 'Демо-данные', registerSuccess: 'Аккаунт создан! Войдите в систему.', errors: { usernameRequired: 'Минимум 3 символа', passwordRequired: 'Минимум 6 символов', invalidEmail: 'Неверный формат email', passwordMismatch: 'Пароли не совпадают' } }
}
